name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: |
          echo "Hello World!"
          echo "Testing the mulitple Lines"
          echo "ipcs -a"
      - name: Ending Greetings
        run : |
          echo "Saying Good bye"
          echo "Will connect again"
